### PR TITLE
FIX: Stop errors when the interaction is not a SLASH command

### PR DESCRIPTION
**Pull request by wrssmithjr04**
Fix for #108

### CODE REVIEW

**Comment by pazzazzo** [comment]
no it's not good, I try that at the beginning but the problem is that even if the interaction received is not SLASH commands, it is still taken into account by the handler,

sorry for the language mistakes, i don't speak english

**Comment by pazzazzo** [comment]
Why is fix for my fix?

My fix work

**Comment by wrssmithjr04** [comment]
> no it's not good, I try that at the beginning but the problem is that even if the interaction received is not SLASH commands, it is still taken into account by the handler,
> 
> 
> 
> sorry for the language mistakes, i don't speak english

Why does it not work? I have been using this in my own bot and it is the same exact change you made.

**Comment by wrssmithjr04** [comment]
> Why is fix for my fix?
> 
> 
> 
> My fix work

This is a fox for your fox because you only edited the js files which are "distribution" files and when it gets compiled again it would be overwritten. You need to edit the ts files to make sure that it doesn't get overwritten and lost and so that it is a part of the source code.

**Pull request closed without merging**
