### PR TITLE
Configurable channel.send() instead of .reply()

### PR DESCRIPTION
**Pull request by wrssmithjr04**
If you need me to make any changes just dm me on discord at wrssmithjr04#8248 or mention me in a comment.

### CODE REVIEW

**Review by Armand95 — APPROVED** [review]

**Comment by bluee-js** [comment]
@wrssmithjr04 Hi, it was really useful for me, but how does it works? And your Discord doesn't exist.

**Comment by wrssmithjr04** [comment]
@bluee-js so you would put reply:true in the config and it would use message.reply instead of message.send

**Comment by bluee-js** [comment]
> @bluee-js so you would put reply:true in the config and it would use message.reply instead of message.send

Omg, you answered quickly. I want to ask you another thing, how can I replace "{AUTHOR}" with message.author?

**Comment by bluee-js** [comment]
@wrssmithjr04 Omg, you answered quickly. I want to ask you another thing, how can I replace "{AUTHOR}" with message.author?

**Comment by wrssmithjr04** [comment]
> @wrssmithjr04 Omg, you answered quickly. I want to ask you another thing, how can I replace "{AUTHOR}" with message.author?

I'm not quite sure what you mean by that.

**Comment by bluee-js** [comment]
@wrssmithjr04 In "messages.json" you can use for example {PREFIX} and it will be replaced with the bot prefix, so how can I use {AUTHOR} and replace with the message's author?

**Comment by wrssmithjr04** [comment]
Not quite sure, I think that would require you to have to modify the code.

**Pull request closed without merging**
