### PR TITLE
Added typescript support

### PR DESCRIPTION
**Pull request by HK-Yeet**
Typescript support for people who like typescript

### CODE REVIEW

**Comment by cursorsdottsx** [comment]
._. u actually changed 33 files?

**Comment by cursorsdottsx** [comment]
wait no u just did `tsc -d` 😂

**Comment by HK-Yeet** [comment]
Nice one cursors

**Comment by HK-Yeet** [comment]
okkkkkkkkk..... github is weird

**Comment by HK-Yeet** [comment]
meant to add embed error options and bot owners ignore cooldown as a seperate pr

**Pull request closed without merging**
